apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "b0k3ts.fullname" . }}-config
  labels:
    {{- include "b0k3ts.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config.yaml | indent 4 }}