apiVersion: v1
kind: Service
metadata:
  name: {{ include "b0k3ts.fullname" . }}
  labels:
    {{- include "b0k3ts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.ui }}
      targetPort: {{ .Values.service.ports.ui }}
      protocol: TCP
      name: http-ui
    - port: {{ .Values.service.ports.server }}
      targetPort: {{ .Values.service.ports.server }}
      protocol: TCP
      name: http-server
  selector:
    {{- include "b0k3ts.selectorLabels" . | nindent 4 }}
